# Real Estate Price Prediction & Investment Insights

In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
pd.set_option('display.max_columns', None)

| Column Name                 | Description |
|-----------------------------|-------------|
| `id`                        | Unique identifier for the house. |
| `No of bedrooms`            | Total number of bedrooms in the house. |
| `No of bathrooms`           | Total number of bathrooms in the house. |
| `living area`               | Total living space in square feet. |
| `lot area`                  | Total land area in square feet. |
| `No of floors`              | Total number of floors in the house. |
| `waterfront present`        | Indicates if the house is near a waterfront (1 = Yes, 0 = No). |
| `No of views`               | Number of times the house has been viewed. |
| `house condition(from 5)`   | Condition rating of the house (out of 5). |
| `house grade`               | Overall house grade based on construction and design. |
| `house area(excluding basement)` | Total living area excluding basement. |
| `Area of the basement`      | Basement area in square feet. |
| `Built Year`                | Year the house was originally built. |
| `Renovation Year`           | Year the house was last renovated. |
| `Postal Code`               | Postal code of the house location. |
| `Lattitude`                 | Latitude coordinate of the house. |
| `Longitude`                 | Longitude coordinate of the house. |
| `living_area_renov`         | Adjusted living area considering renovations. |
| `lot_area_renov`            | Adjusted lot area considering renovations. |
| `No of schools nearby`      | Number of schools in the vicinity. |
| `Distance from the airport` | Distance of the house from the nearest airport (miles/km). |
| `Price`                     | Sale price of the house. |
| `date`                      | Date when the house was sold or listed. |


In [4]:
df= pd.read_csv('House Price India.csv')
df.head()

id   Date  No of bedrooms  No of bathrooms  living area  lot area  \
0  6762810635  42491               4             2.50         2920      4000   
1  6762810998  42491               5             2.75         2910      9480   
2  6762812605  42491               4             2.50         3310     42998   
3  6762812919  42491               3             2.00         2710      4500   
4  6762813105  42491               3             2.50         2600      4750   

   No of floors  waterfront present  No of views  house condition  \
0           1.5                   0            0                5   
1           1.5                   0            0                3   
2           2.0                   0            0                3   
3           1.5                   0            0                4   
4           1.0                   0            0                4   

   house grade  house area(excluding basement)  Area of the basement  \
0            8                            1910                  1010   
1            8                            2910                     0   
2            9                            3310                     0   
3            8                            1880                   830   
4            9                            1700                   900   

   Built Year  Renovation Year  Postal Code  Lattitude  Longitude  \
0        1909                0       122004    52.8878   -114.470   
1        1939                0       122004    52.8852   -114.468   
2        2001                0       122005    52.9532   -114.321   
3        1929                0       122006    52.9047   -114.485   
4        1951                0       122007    52.9133   -114.590   

   living_area_renov  lot_area_renov  No of schools nearby  \
0               2470            4000                     2   
1               2940            6600                     1   
2               3350           42847                     3   
3               2060            4500                     1   
4               2380            4750                     1   

   Distance from the airport    Price  
0                         51  1400000  
1                         53  1200000  
2                         76   838000  
3                         51   805000  
4                         67   790000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14619 entries, 0 to 14618
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id                              14619 non-null  int64  
 1   Date                            14619 non-null  int64  
 2   No of bedrooms                  14619 non-null  int64  
 3   No of bathrooms                 14619 non-null  float64
 4   living area                     14619 non-null  int64  
 5   lot area                        14619 non-null  int64  
 6   No of floors                    14619 non-null  float64
 7   waterfront present              14619 non-null  int64  
 8   No of views                     14619 non-null  int64  
 9   house condition                 14619 non-null  int64  
 10  house grade                     14619 non-null  int64  
 11  house area(excluding basement)  14619 non-null  int64  
 12  Area of the basement            

In [6]:
df.isnull().value_counts()

id     Date   No of bedrooms  No of bathrooms  living area  lot area  No of floors  waterfront present  No of views  house condition  house grade  house area(excluding basement)  Area of the basement  Built Year  Renovation Year  Postal Code  Lattitude  Longitude  living_area_renov  lot_area_renov  No of schools nearby  Distance from the airport  Price
False  False  False           False            False        False     False         False               False        False            False        False                           False                 False       False            False        False      False      False              False           False                 False                      False    14619
Name: count, dtype: int64

In [7]:
df.describe(include='all')

id          Date  No of bedrooms  No of bathrooms  \
count  1.461900e+04  14619.000000    14619.000000     14619.000000   
mean   6.762821e+09  42604.546412        3.379233         2.129557   
std    6.237162e+03     67.343747        0.938655         0.769955   
min    6.762810e+09  42491.000000        1.000000         0.500000   
25%    6.762815e+09  42546.000000        3.000000         1.750000   
50%    6.762821e+09  42600.000000        3.000000         2.250000   
75%    6.762826e+09  42662.000000        4.000000         2.500000   
max    6.762832e+09  42734.000000       33.000000         8.000000   

        living area      lot area  No of floors  waterfront present  \
count  14619.000000  1.461900e+04  14619.000000        14619.000000   
mean    2098.156851  1.509369e+04      1.502326            0.007661   
std      928.218740  3.792089e+04      0.540241            0.087196   
min      370.000000  5.200000e+02      1.000000            0.000000   
25%     1440.000000  5.010500e+03      1.000000            0.000000   
50%     1930.000000  7.620000e+03      1.500000            0.000000   
75%     2570.000000  1.080000e+04      2.000000            0.000000   
max    13540.000000  1.074218e+06      3.500000            1.000000   

        No of views  house condition   house grade  \
count  14619.000000     14619.000000  14619.000000   
mean       0.232848         3.430399      7.682263   
std        0.765651         0.664047      1.174917   
min        0.000000         1.000000      4.000000   
25%        0.000000         3.000000      7.000000   
50%        0.000000         3.000000      7.000000   
75%        0.000000         4.000000      8.000000   
max        4.000000         5.000000     13.000000   

       house area(excluding basement)  Area of the basement    Built Year  \
count                    14619.000000          14619.000000  14619.000000   
mean                      1801.676654            296.480197   1970.929817   
std                        833.737588            448.566731     29.491743   
min                        370.000000              0.000000   1900.000000   
25%                       1200.000000              0.000000   1951.000000   
50%                       1580.000000              0.000000   1975.000000   
75%                       2240.000000            580.000000   1997.000000   
max                       9410.000000           4820.000000   2015.000000   

       Renovation Year    Postal Code     Lattitude     Longitude  \
count     14619.000000   14619.000000  14619.000000  14619.000000   
mean         90.930228  122033.064300     52.792843   -114.403996   
std         416.230218      19.081451      0.137525      0.141325   
min           0.000000  122003.000000     52.385900   -114.709000   
25%           0.000000  122017.000000     52.707600   -114.519000   
50%           0.000000  122032.000000     52.806400   -114.421000   
75%           0.000000  122048.000000     52.908900   -114.315000   
max        2015.000000  122072.000000     53.007600   -113.505000   

       living_area_renov  lot_area_renov  No of schools nearby  \
count       14619.000000    14619.000000          14619.000000   
mean         1996.641836    12754.003078              2.012244   
std           691.078387    26059.234785              0.817312   
min           460.000000      651.000000              1.000000   
25%          1490.000000     5097.500000              1.000000   
50%          1850.000000     7620.000000              2.000000   
75%          2380.000000    10125.000000              3.000000   
max          6110.000000   560617.000000              3.000000   

       Distance from the airport         Price  
count               14619.000000  1.461900e+04  
mean                   64.951433  5.388063e+05  
std                     8.936129  3.672294e+05  
min                    50.000000  7.800000e+04  
25%                    57.000000  3.200000e+05  
50%                    65.000000  4.500000e+05  
75%  

In [8]:
dates = pd.to_datetime(42491, origin='1899-12-30')
print(dates)

1899-12-30 00:00:00.000042491


In [9]:
df["date"] = pd.to_datetime(df["Date"], origin='1899-12-30', unit='D')
df['date'].unique().tolist()

[Timestamp('2016-05-01 00:00:00'),
 Timestamp('2016-05-02 00:00:00'),
 Timestamp('2016-05-03 00:00:00'),
 Timestamp('2016-05-04 00:00:00'),
 Timestamp('2016-05-05 00:00:00'),
 Timestamp('2016-05-06 00:00:00'),
 Timestamp('2016-05-07 00:00:00'),
 Timestamp('2016-05-08 00:00:00'),
 Timestamp('2016-05-09 00:00:00'),
 Timestamp('2016-05-10 00:00:00'),
 Timestamp('2016-05-11 00:00:00'),
 Timestamp('2016-05-12 00:00:00'),
 Timestamp('2016-05-13 00:00:00'),
 Timestamp('2016-05-14 00:00:00'),
 Timestamp('2016-05-15 00:00:00'),
 Timestamp('2016-05-16 00:00:00'),
 Timestamp('2016-05-17 00:00:00'),
 Timestamp('2016-05-18 00:00:00'),
 Timestamp('2016-05-19 00:00:00'),
 Timestamp('2016-05-20 00:00:00'),
 Timestamp('2016-05-21 00:00:00'),
 Timestamp('2016-05-22 00:00:00'),
 Timestamp('2016-05-23 00:00:00'),
 Timestamp('2016-05-24 00:00:00'),
 Timestamp('2016-05-25 00:00:00'),
 Timestamp('2016-05-26 00:00:00'),
 Timestamp('2016-05-27 00:00:00'),
 Timestamp('2016-05-28 00:00:00'),
 Timestamp('2016-05-

In [10]:
df['date']= df['date'].apply(lambda x: str(x).split('-')[1])
df['date'].unique()

array(['05', '06', '07', '08', '09', '10', '11', '12'], dtype=object)

In [11]:
df.drop(columns='Date', inplace=True)

In [12]:
df['No of bathrooms']=df['No of bathrooms'].apply(lambda x:float(str(x).strip()))
df['No of bathrooms'].unique()

array([2.5 , 2.75, 2.  , 3.25, 1.75, 2.25, 1.  , 1.5 , 3.  , 8.  , 3.5 ,
       4.25, 4.  , 5.  , 3.75, 4.5 , 5.75, 1.25, 6.5 , 4.75, 0.75, 5.25,
       5.5 , 6.25, 6.75, 7.5 , 0.5 , 6.  , 7.75])

In [13]:
df.rename(columns={'living area':'living area (sq ft)'})
df['living area'].unique()

array([ 2920,  2910,  3310,  2710,  2600,  3660,  2240,  2390,  2200,
        2820,  1820,  1520,  1750,  2730,  2360,  3240,  2330,  1940,
        2860,  1600,  2190,   880,  2210,  1710,  2680,  2430,  1270,
        2160,   800,  1770,  1970,  1450,  1920,  2000,  1570,  1930,
        1960,  3630,  1320,  1560,  3110,  1090,  1350,  1580,  1160,
        1340,   850,  2540,  1630,  1850,  2090,  1800,  1180,  1480,
        1370,  1200,  1210,   900,  1650,  1010,  2850,  2280,  2530,
       13540,  2220,  4010,  4340,  3190,  1330,  4420,  4490,  3690,
        2170,  3400,  3180,  2350,  2120,  2010,  2450,  2490,  1680,
        2800,  1390,  2440,  1990,  2300,  1670,  1880,  1900,  1140,
        2740,  2550,  1790,  2070,  3200,  2340,  3040,  1840,  1590,
        1410,  1408,  1620,  2110,   840,  2230,  3090,  1571,  1120,
        2370,  2310,  1050,  1550,  1240,  2050,   810,  1490,  4510,
        3760,  3490,  3370,  2690,  3020,  3740,  3880,  2290,  3030,
         930,  3380,

* 1.0 → Single-story house 
* 1.5 → One full floor + partial upper level (e.g., attic or loft)
* 2.0 → Two full floors
* 2.5 → Two full floors + a small attic or loft area
* 3.0 → Three full floors
* 3.5 → Three full floors + an attic or loft area

In [14]:
df['No of floors'].unique()

array([1.5, 2. , 1. , 2.5, 3. , 3.5])

In [15]:
df.rename(columns={'house condition':'house condition(from 5)'}, inplace=True)

- Grade 4-5 → Basic homes
- Grade 6-7 → Standard homes
- rade 8-9 → Upper-middle-class homes
- Grade 10+ → Luxury homes

In [16]:
df['house grade'].unique()

array([ 8,  9, 10,  7,  6, 12, 11,  5,  4, 13])

In [17]:
df['Renovation Year'].unique()

array([   0, 1994, 1954, 2011, 1998, 1992, 1958, 2014, 2002, 2004, 2013,
       1986, 2005, 1990, 2001, 1984, 1956, 2000, 2010, 2003, 1996, 1977,
       2007, 1983, 1970, 1981, 1975, 1971, 1988, 1999, 2009, 1995, 1969,
       1997, 2015, 1982, 1989, 2006, 1985, 1993, 1953, 1955, 1979, 1987,
       1960, 1934, 1945, 2008, 2012, 1980, 1972, 1948, 1978, 1991, 1968,
       1974, 1965, 1946, 1940, 1963, 1976, 1964, 1973, 1967, 1944, 1959,
       1957, 1962])

In [18]:
df[df['Renovation Year']==0].count().sum()

np.int64(320919)

In [19]:
df['Renovation Year']=df['Renovation Year'].apply(lambda x:x if x==0 else 1)

In [20]:
df['Distance from the airport'].unique()

array([51, 53, 76, 67, 72, 71, 73, 69, 80, 74, 55, 70, 75, 60, 58, 50, 64,
       66, 79, 78, 61, 52, 68, 62, 63, 77, 56, 65, 57, 59, 54])

In [21]:
df.to_csv('cleaned data.csv')